### ISSUE TITLE
Outputs the input prompt

### ISSUE THREAD

**Issue by austinmw** [SingularityLabs-ai/chatgpt-scientific-publications-extension#5]
**Describe the bug**
![image](https://github.com/SingularityLabs-ai/chatgpt-scientific-publications-extension/assets/12224358/e7261742-fe7d-4a8e-95d0-22700c5d437d)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Arc

**Comment by DENGARDEN** [comment]
I experienced the same event here. ChatGPT web app shows "There was an error generating a response". It might be the effect of the recent update.

**Comment by ishandutta2007** [comment]
@austinmw @DENGARDEN is the issue still there ?

**Comment by DENGARDEN** [comment]
@ishandutta2007 Nope. I've used this product recently, and there is no issue I can find. Thanks!
